# -*- coding: utf-8 -*-
"""Maize_Yield_Pridiction_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxT_0jxkxiseFGS2oPrGJmaVsG_ZxFLn
"""

import pandas as pd

DATA_PATH = "/content/Corn_Cultivated_Soil_Tested_Dataset.csv"

df = pd.read_csv(DATA_PATH)
print(df.shape)

df.head()

"""# Understand the Dataset"""

print("Total columns:", len(df.columns))
for c in df.columns:
    print(c)

"""> ***Check data types***


"""

df.dtypes

"""> ***Check missing values***


"""

missing = df.isna().sum().sort_values(ascending=False)
missing[missing > 0]

df.describe().T

print("Districts:", sorted(df["district"].unique()))
print("Seed varieties:", sorted(df["seed_variety"].unique()))
print("Seasons:", sorted(df["season"].unique()))

print("Duplicate rows:", df.duplicated().sum())

# Temperature sanity check

bad_temp = df[df["max_temperature_c"] < df["avg_temperature_c"]]
print("Rows with max_temperature_c < avg_temperature_c:", len(bad_temp))
bad_temp[["avg_temperature_c","max_temperature_c"]].head(10)

import pandas as pd

tmp = df.copy()
tmp["planting_date_dt"] = pd.to_datetime(tmp["planting_date"], format="%m/%d/%Y", errors="coerce")
tmp["first_fert_dt"] = pd.to_datetime(tmp["first_fert_date"], format="%m/%d/%Y", errors="coerce")
tmp["second_fert_dt"] = pd.to_datetime(tmp["second_fert_date"], format="%m/%d/%Y", errors="coerce")

bad_first = tmp[tmp["first_fert_dt"] < tmp["planting_date_dt"]]
bad_second = tmp[tmp["second_fert_dt"] < tmp["first_fert_dt"]]

print("First fert before planting:", len(bad_first))
print("Second fert before first fert:", len(bad_second))

checks = {
    "soil_ph_out_of_range": ((df["soil_ph"] < 3.5) | (df["soil_ph"] > 9.0)).sum(),
    "humidity_out_of_range": ((df["avg_humidity_pct"] < 0) | (df["avg_humidity_pct"] > 100)).sum(),
    "negative_rainfall_30d": (df["rainfall_30d_mm"] < 0).sum(),
    "negative_seasonal_rainfall": (df["seasonal_rainfall_mm"] < 0).sum(),
    "negative_yield": (df["yield_t_ha"] < 0).sum(),
    "field_size_too_small": (df["field_size_ha"] < 0.05).sum(),
}
checks

"""

> ***Target variable check (yield) distribution***

"""

import matplotlib.pyplot as plt

plt.figure()
df["yield_t_ha"].hist(bins=30)
plt.title("Yield (t/ha) distribution")
plt.xlabel("yield_t_ha")
plt.ylabel("count")
plt.show()

print("Yield min:", df["yield_t_ha"].min())
print("Yield max:", df["yield_t_ha"].max())
print("Yield mean:", df["yield_t_ha"].mean())

"""# Data Cleaning

> ***Data Cleaning + Feature Engineering***
"""

df2 = df.copy()
print(df2.shape)

#Convert date columns to datetime
import pandas as pd

df2["planting_date_dt"] = pd.to_datetime(df2["planting_date"], format="%m/%d/%Y", errors="coerce")
df2["first_fert_dt"]    = pd.to_datetime(df2["first_fert_date"], format="%m/%d/%Y", errors="coerce")
df2["second_fert_dt"]   = pd.to_datetime(df2["second_fert_date"], format="%m/%d/%Y", errors="coerce")

df2[["planting_date", "planting_date_dt", "first_fert_date", "first_fert_dt"]].head()

#Fix the 2 temperature errors (swap values safely)
mask_temp = df2["max_temperature_c"] < df2["avg_temperature_c"]
df2.loc[mask_temp, ["avg_temperature_c", "max_temperature_c"]] = df2.loc[
    mask_temp, ["max_temperature_c", "avg_temperature_c"]
].values

print("Remaining temp errors:", (df2["max_temperature_c"] < df2["avg_temperature_c"]).sum())

#Fix fertilizer-before-planting errors (shift fertilizer dates forward)
mask_bad_first = df2["first_fert_dt"] < df2["planting_date_dt"]
df2.loc[mask_bad_first, "first_fert_dt"] = df2.loc[mask_bad_first, "planting_date_dt"] + pd.to_timedelta(14, unit="D")

mask_bad_second = df2["second_fert_dt"] < df2["first_fert_dt"]
df2.loc[mask_bad_second, "second_fert_dt"] = df2.loc[mask_bad_second, "first_fert_dt"] + pd.to_timedelta(21, unit="D")

print("First fert before planting:", (df2["first_fert_dt"] < df2["planting_date_dt"]).sum())
print("Second fert before first fert:", (df2["second_fert_dt"] < df2["first_fert_dt"]).sum())

#Feature engineering from dates (create numeric columns)
df2["planting_year"] = df2["planting_date_dt"].dt.year
df2["planting_month_from_date"] = df2["planting_date_dt"].dt.month
df2["planting_dayofyear"] = df2["planting_date_dt"].dt.dayofyear

df2["days_to_first_fert"] = (df2["first_fert_dt"] - df2["planting_date_dt"]).dt.days
df2["days_between_ferts"] = (df2["second_fert_dt"] - df2["first_fert_dt"]).dt.days

df2[["planting_year","planting_month_from_date","planting_dayofyear","days_to_first_fert","days_between_ferts"]].head()

df2 = df2.drop(columns=[
    "planting_date", "first_fert_date", "second_fert_date",
    "planting_date_dt", "first_fert_dt", "second_fert_dt"
])

print(df2.shape)
df2.head()

# Clean extra spaces in ALL categorical columns
import re

cat_cols_all = df2.select_dtypes(include="object").columns

for col in cat_cols_all:
    df2[col] = (
        df2[col].astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)  # remove double spaces
    )

# Standardize soil_type names -> short codes
# Make soil_type consistent
soil_map = {
    "Immature Brown Loams": "IBL",
    "IMMATURE BROWN LOAMS": "IBL",
    "Low Humic Gleys": "LHG",
    "LOW HUMIC GLEYS": "LHG",
    "LOW HUMIC GLEYS ": "LHG",
}

df2["soil_type"] = df2["soil_type"].replace(soil_map)

# Catch slight spelling/spacing variations (safe)
df2.loc[df2["soil_type"].str.contains(r"immature\s*brown\s*loams", case=False, na=False), "soil_type"] = "IBL"
df2.loc[df2["soil_type"].str.contains(r"low\s*humic\s*gleys?", case=False, na=False), "soil_type"] = "LHG"

#Check soil types (and detect “new/unknown” ones)
print("Unique soil_type values:", sorted(df2["soil_type"].unique()))
print("\nSoil type counts:")
print(df2["soil_type"].value_counts())

sorted(df2["soil_type"].unique())

"""# Encoding + Preprocessing Pipeline (OneHotEncoder + Imputer)

> ***Define target (y) and features (X)***
"""

target = "yield_t_ha"

X = df2.drop(columns=[target])
y = df2[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

"""
> ***Separate categorical vs numeric columns***
"""

cat_cols = X.select_dtypes(include=["object"]).columns.tolist()
num_cols = X.select_dtypes(exclude=["object"]).columns.tolist()

print("Categorical columns:", cat_cols)
print("Numeric columns:", num_cols)
print("\nCounts -> Categorical:", len(cat_cols), "Numeric:", len(num_cols))

"""

> ***Build the preprocessing pipeline***

"""

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, num_cols),
        ("cat", categorical_transformer, cat_cols)
    ]
)

preprocess

"""

> ***Train/Test split (80/20)***

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train X:", X_train.shape, "Test X:", X_test.shape)
print("Train y:", y_train.shape, "Test y:", y_test.shape)

"""# Train 3 Models + Evaluate + Pick Best

```
# Ready to Train : LinearRegression, RandomForestRegressor, XGBoostRegressor
```
And evaluate using:

*   MAE (lower is better)

*   RMSE (lower is better)

*   R² (higher is better, max 1)

> Imports for Models
"""

#Install XGBoost
!pip -q install xgboost

#Import other libraries
import numpy as np
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

#Create an evaluation function
def evaluate(pipe, X_test, y_test, name="Model"):
    preds = pipe.predict(X_test)
    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2 = r2_score(y_test, preds)

    print(name)
    print("MAE :", round(mae, 4))
    print("RMSE:", round(rmse, 4))
    print("R2  :", round(r2, 4))

    return mae, rmse, r2

"""

> ***Train Model 1 — Linear Regression***

"""

lin_pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", LinearRegression())
])

lin_pipe.fit(X_train, y_train)

lin_mae, lin_rmse, lin_r2 = evaluate(lin_pipe, X_test, y_test, "LinearRegression")

"""

> ***Train Model 2 — RandomForestRegressor***

"""

rf_pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])

rf_pipe.fit(X_train, y_train)

rf_mae, rf_rmse, rf_r2 = evaluate(rf_pipe, X_test, y_test, "RandomForestRegressor")

"""

> ***Train Model 3 — XGBoostRegressor***

"""

xgb_pipe = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", XGBRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=6,
        subsample=0.9,
        colsample_bytree=0.9,
        random_state=42
    ))
])

xgb_pipe.fit(X_train, y_train)

xgb_mae, xgb_rmse, xgb_r2 = evaluate(xgb_pipe, X_test, y_test, "XGBoostRegressor")

"""

> ***Model Comparison Table***
"""

results_df = pd.DataFrame([
    ["LinearRegression", lin_mae, lin_rmse, lin_r2],
    ["RandomForestRegressor", rf_mae, rf_rmse, rf_r2],
    ["XGBoostRegressor", xgb_mae, xgb_rmse, xgb_r2],
], columns=["Model", "MAE", "RMSE", "R2"]).sort_values("RMSE")

results_df

"""# Cross Validation"""

#Import cross_val_score
from sklearn.model_selection import cross_val_score

"""

> ***Cross-validate LinearRegression (5 folds)***

"""

lin_cv_rmse = -cross_val_score(
    lin_pipe, X, y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

print("LinearRegression CV RMSE mean:", round(lin_cv_rmse.mean(), 4))
print("LinearRegression CV RMSE std :", round(lin_cv_rmse.std(), 4))

"""

> ***Cross-validate RandomForest (5 folds)***

"""

rf_cv_rmse = -cross_val_score(
    rf_pipe, X, y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

print("RandomForest CV RMSE mean:", round(rf_cv_rmse.mean(), 4))
print("RandomForest CV RMSE std :", round(rf_cv_rmse.std(), 4))

"""

> ***Cross-validate XGBoost (5 folds)***

"""

xgb_cv_rmse = -cross_val_score(
    xgb_pipe, X, y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

print("XGBoost CV RMSE mean:", round(xgb_cv_rmse.mean(), 4))
print("XGBoost CV RMSE std :", round(xgb_cv_rmse.std(), 4))

"""

> ***CV comparison table***

"""

cv_df = pd.DataFrame([
    ["LinearRegression", lin_cv_rmse.mean(), lin_cv_rmse.std()],
    ["RandomForestRegressor", rf_cv_rmse.mean(), rf_cv_rmse.std()],
    ["XGBoostRegressor", xgb_cv_rmse.mean(), xgb_cv_rmse.std()],
], columns=["Model", "CV_RMSE_Mean", "CV_RMSE_Std"]).sort_values("CV_RMSE_Mean")

cv_df

"""# Save Best Model (XGBoost pipeline)"""

#Save pipeline

import joblib
joblib.dump(xgb_pipe, "best_yield_model_xgb.pkl")
print("Saved: best_yield_model_xgb.pkl")

#Download
from google.colab import files
files.download("best_yield_model_xgb.pkl")



"""# Feature Importance (XGBoost) + Plot

> ***Fit XGBoost pipeline again (make sure it’s trained)***
"""

xgb_pipe.fit(X_train, y_train)
print("XGBoost pipeline trained.")

# Get the encoded feature names after preprocessing
ohe = xgb_pipe.named_steps["preprocess"].named_transformers_["cat"].named_steps["onehot"]

cat_feature_names = ohe.get_feature_names_out(cat_cols)
all_feature_names = np.concatenate([num_cols, cat_feature_names])

print("Total final features after encoding:", len(all_feature_names))

"""

> ***Extract XGBoost feature importances + create Top 15 table***

"""

xgb_model = xgb_pipe.named_steps["model"]

importances = xgb_model.feature_importances_

fi = pd.DataFrame({
    "feature": all_feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

fi.head(15)

"""

> ***Plot Top 15 feature importances***

"""

import matplotlib.pyplot as plt

top_n = 15
top_fi = fi.head(top_n).iloc[::-1]  # reverse for nice plotting

plt.figure(figsize=(10, 6))
plt.barh(top_fi["feature"], top_fi["importance"])
plt.title("Top 15 Feature Importances (XGBoost)")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.tight_layout()
plt.show()

"""

> ***Check where rainfall + seed_variety features are ranked (Top 50 view)***

"""

# Show top 50
fi.head(50)

fi[fi["feature"].str.contains("rainfall|seed_variety", case=False, na=False)].head(30)

"""

> ***Group importance by original column***

"""

# Map each encoded feature back to its original column name
def base_feature_name(feat: str) -> str:
    for c in cat_cols:
        prefix = c + "_"
        if feat.startswith(prefix):
            return c
    return feat  # numeric stays same

fi["base_feature"] = fi["feature"].apply(base_feature_name)

group_imp = (
    fi.groupby("base_feature")["importance"]
      .sum()
      .sort_values(ascending=False)
      .reset_index()
)

group_imp.head(20)

"""

> ***Plot grouped importance***

"""

import matplotlib.pyplot as plt

top_n = 15
tmp = group_imp.head(top_n).iloc[::-1]

plt.figure(figsize=(10, 6))
plt.barh(tmp["base_feature"], tmp["importance"])
plt.title("Top 15 Grouped Feature Importances (XGBoost)")
plt.xlabel("Total Importance (grouped)")
plt.ylabel("Original Feature")
plt.tight_layout()
plt.show()

fi[fi["base_feature"] == "seed_variety"].head(20)

"""*Top-15 shows individual encoded features. Since seed_variety is one-hot encoded, its influence is split across multiple columns, so it may not appear in Top-15. When I group importances by original column, seed variety and rainfall influence become visible.*

"""

#Predict on test set
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

y_pred = xgb_pipe.predict(X_test)

#Calculate metrics
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

print("R² Score:", round(r2, 4))
print("RMSE:", round(rmse, 4))
print("MAE:", round(mae, 4))

# Testing MAPE Value
mape = np.mean(np.abs((y_test - y_pred) / y_test)) * 100
print("MAPE (%):", round(mape, 2))

"""

> XGBoost Regressor – Prediction + Accuracy (MAPE-based)




"""

# XGBRegressior Model Accuracy using MAPE
accuracy = 100 - mape
print("Accuracy (%):", round(accuracy, 2))

"""

> Linear Regression – Prediction + Accuracy (MAPE-based)

"""

# ===============================
# Linear Regression Evaluation
# ===============================

# Predict
y_pred_lin = lin_pipe.predict(X_test)

# Metrics
r2_lin = r2_score(y_test, y_pred_lin)
rmse_lin = np.sqrt(mean_squared_error(y_test, y_pred_lin))
mae_lin = mean_absolute_error(y_test, y_pred_lin)

print("Linear Regression Results")
print("R² Score:", round(r2_lin, 4))
print("RMSE:", round(rmse_lin, 4))
print("MAE:", round(mae_lin, 4))

# MAPE
mape_lin = np.mean(np.abs((y_test - y_pred_lin) / y_test)) * 100
accuracy_lin = 100 - mape_lin

print("MAPE (%):", round(mape_lin, 2))
print("Accuracy (%):", round(accuracy_lin, 2))

"""

> Random Forest – Prediction + Accuracy (MAPE-based)
"""

# ===============================
# Random Forest Evaluation
# ===============================

# Predict
y_pred_rf = rf_pipe.predict(X_test)

# Metrics
r2_rf = r2_score(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae_rf = mean_absolute_error(y_test, y_pred_rf)

print("Random Forest Results")
print("R² Score:", round(r2_rf, 4))
print("RMSE:", round(rmse_rf, 4))
print("MAE:", round(mae_rf, 4))

# MAPE
mape_rf = np.mean(np.abs((y_test - y_pred_rf) / y_test)) * 100
accuracy_rf = 100 - mape_rf

print("MAPE (%):", round(mape_rf, 2))
print("Accuracy (%):", round(accuracy_rf, 2))

"""

> XGBoost Regression – Prediction + Accuracy (MAPE-based)

"""

# ===============================
# XGBoost Regression Evaluation
# ===============================

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Predict
y_pred_xgb = xgb_pipe.predict(X_test)

# Metrics
r2_xgb = r2_score(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)

print("XGBoost Regression Results")
print("R² Score:", round(r2_xgb, 4))
print("RMSE:", round(rmse_xgb, 4))
print("MAE:", round(mae_xgb, 4))

# MAPE
mape_xgb = np.mean(np.abs((y_test - y_pred_xgb) / y_test)) * 100
accuracy_xgb = 100 - mape_xgb

print("MAPE (%):", round(mape_xgb, 2))
print("Accuracy (%):", round(accuracy_xgb, 2))

comparison_df = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "XGBoost"],
    "R²": [r2_lin, r2_rf, r2_xgb],
    "RMSE": [rmse_lin, rmse_rf, rmse_xgb],
    "MAE": [mae_lin, mae_rf, mae_xgb],
    "MAPE (%)": [mape_lin, mape_rf, mape_xgb],
    "Accuracy (%)": [accuracy_lin, accuracy_rf, accuracy_xgb]
}).round(3)

comparison_df.sort_values("Accuracy (%)", ascending=False)

"""

> Accuracy Comparison Bar Chart

"""

import matplotlib.pyplot as plt

# Model names and accuracies
models = ["Linear Regression", "Random Forest", "XGBoost"]
accuracies = [accuracy_lin, accuracy_rf, accuracy_xgb]

# Define 3 different colors
colors = ["#6baed6", "#74c476", "#fd8d3c"]
# blue, green, orange (research-paper friendly)

plt.figure(figsize=(8, 5))

bars = plt.bar(models, accuracies, color=colors)

# Add value labels on bars
for bar in bars:
    yval = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        yval + 0.5,
        f"{yval:.2f}%",
        ha="center",
        va="bottom",
        fontsize=10
    )

# Axis & title
plt.ylim(0, 100)
plt.ylabel("Accuracy (%)")
plt.xlabel("Models")
plt.title("Accuracy of Different Regression Models")

# Grid (optional but looks professional)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.tight_layout()
plt.show()

